# Generated by Django 3.0.1 on 2020-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_lg_0',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_lg_1',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_lg_2',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_lg_3',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_lg_4',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_sm_0',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_sm_1',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_sm_2',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_sm_3',
        ),
        migrations.RemoveField(
            model_name='pizzatype',
            name='price_sm_4',
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='large_0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='large_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='large_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='large_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='large_4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='small_0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='small_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='small_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='small_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='small_4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
